-- Test script using actual data from successful form submission
-- This uses the exact field values that were captured in the browser console

-- Insert test record with actual form data (minus the signature)
INSERT INTO patients (
  nombre_completo, 
  tipo_identificacion, 
  numero_identidad,
  fecha_nacimiento,
  edad,
  sexo,
  tipo_sangre,
  codigopais,
  telefono,
  direccion,
  escolaridad,
  estado_civil,
  email,
  trabajo,
  contacto_emergencia,
  contacto_telefono,
  medico_cabecera,
  doctor,
  fecha_inicio,
  seguro,
  poliza,
  contacto,
  enfermedades,
  alergias,
  medicamentos,
  hospitalizaciones,
  cirugias,
  embarazo,
  antecedentes_familiares,
  vacunas,
  observaciones_medicas,
  fuma,
  alcohol,
  alcohol_frecuencia,
  drogas,
  cafe,
  cantidad_tazas,
  objetos,
  hielo,
  bruxismo,
  boca,
  refrescos,
  dulces,
  pegajosos,
  azucarados,
  obs,
  visitas_dentista,
  obsgen,
  motivo,
  historial,
  encias,
  dolor,
  dolor_cabeza,
  chasquidos,
  dolor_oido,
  suction_digital,
  ortodoncia,
  reaccion_adversa_anestesico,
  tipo_reaccion,
  experiencia_traumatica,
  que_sucedio,
  protesis,
  protesis_tipo,
  protesis_nocturno,
  sensibilidad,
  tipo_sensibilidad,
  ultima_limpieza,
  f_cepillado,
  tipocepillo,
  pastadental,
  cambio_cepillo,
  hilo_dental,
  enjuague_bucal
) VALUES (
  'Test Patient',
  'HN',
  '0501-1988-03242',
  '1987-04-04',
  38,
  'masculino',
  'O+',
  504,
  '9771-5979',
  'Ciudad Morazan, Choloma',
  'Bachillerato',
  'Union Libre',
  'test@example.com',
  'Zero Variance',
  'Sully G. Calix',
  '3269-1484',
  'NA',
  'Dra. Sully Calix',
  '2026-01-08',
  'IHSS',
  '0501198703242',
  'Facebook',
  'Diabetes',
  'Polvo',
  'Metformina',
  'Si',
  'Hernia',
  'no',
  'HTA',
  'Covid',
  'Debe beber mas agua',
  'no',
  'si',
  'Social',
  'no',
  'si',
  1,
  'no',
  'no',
  'no',
  'no',
  'si',
  'si',
  'si',
  'si',
  'Debe dormir mejor',
  '4 meses',
  'Debe regresar',
  'Revision',
  'Limpiezas',
  'no',
  'no',
  'no',
  'no',
  'no',
  'no',
  'no',
  'no',
  'no',
  'no',
  'no',
  'no',  -- New field: reaccion_adversa_anestesico
  NULL,  -- New field: tipo_reaccion (NULL when reaccion is 'no')
  'no',  -- New field: experiencia_traumatica
  NULL,  -- New field: que_sucedio (NULL when experiencia is 'no')
  'si',
  'Parcial Removible',
  'no',
  'si',
  'desconocido',
  '6 meses',
  2,
  'Suave',
  'Total 12',
  '3 meses',
  'si',
  'no'
);

-- Test if the insert works
SELECT 
  nombre_completo,
  reaccion_adversa_anestesico,
  tipo_reaccion,
  experiencia_traumatica,
  que_sucedio
FROM patients 
WHERE nombre_completo = 'Test Patient';
