import { AVAILABLE_DOCTORS } from '../config/doctors';

export interface Patient {
  paciente_id?: string;
  codigo_interno?: string;
  nombre_completo: string;
  tipo_identificacion: 'HN' | 'US' | 'GT' | 'SV' | 'NI' | 'ES' | 'OTRO';
  otro_tipo_identificacion?: string;
  numero_identidad: string;
  fecha_nacimiento: string;
  edad?: number;
  representante_legal?: string;
  parentesco?: 'padre' | 'madre' | 'tutor' | 'otro';
  otro_parentesco?: string;
  rep_celular?: string;
  codigopaisrepresentante?: string;
  rep_pais_codigo?: string;
  sexo: 'masculino' | 'femenino' | 'otro';
  otro_genero?: string;
  tipo_sangre: 'A+' | 'A-' | 'B+' | 'B-' | 'AB+' | 'AB-' | 'O+' | 'O-' | 'Desconocido';
  telefono?: string;
  codigopais?: string;
  pais_codigo?: string;
  direccion: string;
  escolaridad: string;
  estado_civil: 'Soltero' | 'Casado' | 'Viudo' | 'Divorciado' | 'Union Libre';
  email?: string;
  trabajo?: string;
  contacto_emergencia: string;
  contacto_telefono: string;
  codigopaisemergencia?: string;
  contacto_pais_codigo?: string;
  medico_cabecera?: string;
  doctor: typeof AVAILABLE_DOCTORS[number]['name'] | 'otro';
  otro_doctor?: string;
  fecha_inicio: string;
  seguro: 'Ninguno' | 'IHSS' | 'Mapfre' | 'Palic' | 'ficohsa_seguros' | 'otro';
  otro_seguro?: string;
  poliza?: string;
  contacto?: string;
  enfermedades: string;
  alergias: string;
  medicamentos: string;
  hospitalizaciones: string;
  cirugias: string;
  embarazo?: 'no' | 'si';
  semanas_embarazo?: number;
  medicamentos_embarazo?: string;
  embarazo_fecha_fin?: string;
  embarazo_activo?: boolean;
  antecedentes_familiares: string;
  vacunas?: string;
  observaciones_medicas?: string;
  fuma: 'no' | 'si';
  fuma_cantidad?: number;
  fuma_frecuencia?: 'Social' | 'Diario' | 'Semanal' | 'Mensual' | 'Ocasional';
  alcohol: 'no' | 'si';
  alcohol_frecuencia?: 'Social' | 'Diario' | 'Semanal' | 'Mensual' | 'Ocasional';
  drogas: 'no' | 'si';
  tipo_droga?: string;
  drogas_frecuencia?: 'Social' | 'Diario' | 'Semanal' | 'Mensual' | 'Ocasional';
  cafe: 'no' | 'si';
  cantidad_tazas?: number;
  objetos: 'no' | 'si';
  morder?: string;
  hielo: 'no' | 'si';
  boca: 'no' | 'si';
  refrescos: 'no' | 'si';
  dulces: 'no' | 'si';
  pegajosos: 'no' | 'si';
  azucarados: 'no' | 'si';
  obs?: string;
  visitas_dentista?: string;
  obsgen?: string;
  motivo: string;
  historial?: string;
  encias: 'no' | 'si';
  sangrado_encia?: string;
  dolor: 'no' | 'si';
  dolor_masticar?: string;
  dolor_cabeza: 'no' | 'si';
  dolor_cabeza_detalle?: string;
  chasquidos: 'no' | 'si';
  chasquidos_mandibulares?: string;
  dolor_oido: 'no' | 'si';
  dolor_oido_detalle?: string;
  suction_digital: 'no' | 'si';
  ortodoncia: 'no' | 'si';
  orto_finalizado?: 'no' | 'si';
  orto_motivo_no_finalizado?: string;
  protesis: 'no' | 'si';
  protesis_tipo?: 'Removible' | 'Fija' | 'Implante';
  protesis_nocturno?: 'no' | 'si';
  sensibilidad: 'no' | 'si';
  tipo_sensibilidad?: string;
  bruxismo: 'no' | 'si';
  tipo_bruxismo?: 'diurno' | 'nocturno' | 'ambos';
  ultima_limpieza?: string;
  f_cepillado: number;
  tipocepillo?: string;
  pastadental: string;
  cambio_cepillo: string;
  hilo_dental: 'no' | 'si';
  enjuague_bucal: 'no' | 'si';
  necesita_ortodoncia: 'no' | 'si' | 'en_tratamiento';
  detalles_ortodoncia?: string;
  relacion_molar?: 'clase1' | 'clase2_div1' | 'clase2_div2' | 'clase3';
  relacion_canina?: 'clase1' | 'clase2' | 'clase3';
  tipo_mordida?: 'normal' | 'abierta' | 'cruzada' | 'bordeaborde' | 'profunda';
  apiñamiento?: 'ninguno' | 'leve' | 'medio' | 'grave';
  espacios?: 'ninguno' | 'diastemas' | 'exodonciaprevias';
  lineamedia?: 'centrada' | 'desviada_derecha' | 'desviada_izquierda';
  diagnostico?: string;
  tipo_aparatologia?: 'brackets_metalicos' | 'brackets_esteticos' | 'ortodoncia_lingual' | 'alineadores_invisalign' | 'aparato_removible' | 'expansor_palatino' | 'retenedores' | 'aparato_funcional' | 'otro';
  otro_aparatologia?: string;
  tratamiento?: string;
  documentos?: string[];
  observaciones_plan?: string;
  firma_digital?: string;
  is_historical?: boolean;
  matchedFields?: string[];
  score?: number;
}
