-- Create patient_credits table for tracking overpayment credits (Saldo Positivo)
CREATE TABLE IF NOT EXISTS patient_credits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    paciente_id UUID NOT NULL REFERENCES patients(paciente_id) ON DELETE CASCADE,
    monto DECIMAL(10,2) NOT NULL CHECK (monto > 0),
    moneda VARCHAR(3) NOT NULL DEFAULT 'HNL' CHECK (moneda IN ('HNL', 'USD')),
    origen_pago_id UUID REFERENCES payments(id) ON DELETE SET NULL,
    tratamiento_completado_id UUID REFERENCES tratamientos_completados(id) ON DELETE SET NULL,
    usado_en_pago_id UUID REFERENCES payments(id) ON DELETE SET NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'disponible' CHECK (estado IN ('disponible', 'usado', 'cancelado')),
    notas TEXT,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_patient_credits_paciente_id ON patient_credits(paciente_id);
CREATE INDEX IF NOT EXISTS idx_patient_credits_estado ON patient_credits(estado);
CREATE INDEX IF NOT EXISTS idx_patient_credits_moneda ON patient_credits(moneda);
CREATE INDEX IF NOT EXISTS idx_patient_credits_origen_pago_id ON patient_credits(origen_pago_id);

-- Enable RLS
ALTER TABLE patient_credits ENABLE ROW LEVEL SECURITY;

-- RLS policies
DROP POLICY IF EXISTS "Users can view patient credits" ON patient_credits;
CREATE POLICY "Users can view patient credits" ON patient_credits
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert patient credits" ON patient_credits;
CREATE POLICY "Users can insert patient credits" ON patient_credits
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Users can update patient credits" ON patient_credits;
CREATE POLICY "Users can update patient credits" ON patient_credits
    FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Users can delete patient credits" ON patient_credits;
CREATE POLICY "Users can delete patient credits" ON patient_credits
    FOR DELETE USING (true);

-- Enable realtime
ALTER PUBLICATION supabase_realtime ADD TABLE patient_credits;

-- Function: Auto-create patient credit when payment causes overpayment
CREATE OR REPLACE FUNCTION handle_overpayment_credit()
RETURNS TRIGGER AS $$
DECLARE
    v_total_final DECIMAL(10,2);
    v_total_paid DECIMAL(10,2);
    v_overpayment DECIMAL(10,2);
    v_paciente_id UUID;
    v_moneda VARCHAR(3);
BEGIN
    -- Get treatment info
    SELECT tc.total_final, tc.paciente_id, tc.moneda
    INTO v_total_final, v_paciente_id, v_moneda
    FROM tratamientos_completados tc
    WHERE tc.id = NEW.tratamiento_completado_id;

    IF v_total_final IS NULL THEN
        RETURN NEW;
    END IF;

    -- Calculate total paid including this new payment
    SELECT COALESCE(SUM(
        CASE 
            WHEN monto_convertido IS NOT NULL THEN monto_convertido
            ELSE monto_pago
        END
    ), 0)
    INTO v_total_paid
    FROM payments
    WHERE tratamiento_completado_id = NEW.tratamiento_completado_id;

    -- If overpaid, create credit for the difference
    v_overpayment := v_total_paid - v_total_final;
    IF v_overpayment > 0 THEN
        INSERT INTO patient_credits (paciente_id, monto, moneda, origen_pago_id, tratamiento_completado_id, estado, notas)
        VALUES (
            v_paciente_id,
            v_overpayment,
            v_moneda,
            NEW.id,
            NEW.tratamiento_completado_id,
            'disponible',
            'Saldo positivo generado por sobre-pago'
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: fires after payment insert to check for overpayment
DROP TRIGGER IF EXISTS trigger_handle_overpayment_credit ON payments;
CREATE TRIGGER trigger_handle_overpayment_credit
    AFTER INSERT ON payments
    FOR EACH ROW
    EXECUTE FUNCTION handle_overpayment_credit();

-- Function: Cancel credit when source payment is deleted
CREATE OR REPLACE FUNCTION handle_payment_delete_credit()
RETURNS TRIGGER AS $$
BEGIN
    -- Mark any credits generated by this payment as cancelled
    UPDATE patient_credits
    SET estado = 'cancelado',
        actualizado_en = NOW()
    WHERE origen_pago_id = OLD.id
    AND estado = 'disponible';

    -- Also release any credit that was USED by this payment
    UPDATE patient_credits
    SET estado = 'disponible',
        usado_en_pago_id = NULL,
        actualizado_en = NOW()
    WHERE usado_en_pago_id = OLD.id
    AND estado = 'usado';

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- Trigger: fires after payment delete to cancel associated credits
DROP TRIGGER IF EXISTS trigger_handle_payment_delete_credit ON payments;
CREATE TRIGGER trigger_handle_payment_delete_credit
    AFTER DELETE ON payments
    FOR EACH ROW
    EXECUTE FUNCTION handle_payment_delete_credit();

-- Function: Get available credit for a patient in a specific currency
CREATE OR REPLACE FUNCTION get_patient_available_credit(
    p_paciente_id UUID,
    p_moneda VARCHAR(3) DEFAULT 'HNL'
)
RETURNS DECIMAL(10,2) AS $$
DECLARE
    v_available DECIMAL(10,2);
BEGIN
    SELECT COALESCE(SUM(monto), 0)
    INTO v_available
    FROM patient_credits
    WHERE paciente_id = p_paciente_id
    AND moneda = p_moneda
    AND estado = 'disponible';

    RETURN v_available;
END;
$$ LANGUAGE plpgsql;
