-- Delete (instead of cancel) patient credits when their originating payment is
-- deleted.
--
-- Problem: `handle_payment_delete_credit` only flipped the credit to
-- `cancelado`, so a "Saldo Positivo" row stayed in `patient_credits` forever
-- after the payment that generated it was removed. The money is gone, so the
-- derived credit must be removed too.
--
-- Run this in the Supabase SQL editor.

CREATE OR REPLACE FUNCTION handle_payment_delete_credit()
RETURNS TRIGGER AS $$
BEGIN
    -- Delete credits that were generated by this payment (overpayment / advance
    -- origin). Runs BEFORE DELETE so origen_pago_id still points at this row.
    DELETE FROM patient_credits
    WHERE origen_pago_id = OLD.id;

    -- Release credits that were consumed by this payment (saldo-positivo usage)
    -- back to available: that overpayment still belongs to the patient.
    UPDATE patient_credits
    SET estado = 'disponible',
        usado_en_pago_id = NULL,
        actualizado_en = NOW()
    WHERE usado_en_pago_id = OLD.id
      AND estado = 'usado';

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_handle_payment_delete_credit ON payments;
CREATE TRIGGER trigger_handle_payment_delete_credit
    BEFORE DELETE ON payments
    FOR EACH ROW
    EXECUTE FUNCTION handle_payment_delete_credit();

-- One-time cleanup: remove credits previously cancelled by the old trigger
-- behaviour (they no longer reference any payment).
DELETE FROM patient_credits
WHERE estado = 'cancelado'
  AND origen_pago_id IS NULL
  AND usado_en_pago_id IS NULL;
