-- Fix credit cleanup when a payment is deleted.
--
-- Root cause: handle_payment_delete_credit ran as an AFTER DELETE trigger, but
-- the payments -> patient_credits FK uses ON DELETE SET NULL, so by the time the
-- AFTER trigger fired, origen_pago_id / usado_en_pago_id were already NULL and
-- the cleanup UPDATE matched nothing — leaving orphaned patient_credits rows
-- (e.g. a "disponible" credit with no origin payment that keeps showing the
-- Saldo Positivo amount in the payment modal after the payment is gone).
--
-- Solution: make the cleanup a BEFORE DELETE trigger so it runs while the
-- credit references still point at the payment being deleted.

CREATE OR REPLACE FUNCTION handle_payment_delete_credit()
RETURNS TRIGGER AS $$
BEGIN
    -- Cancel credits that were generated by this payment (overpayment origin)
    UPDATE patient_credits
    SET estado = 'cancelado',
        actualizado_en = NOW()
    WHERE origen_pago_id = OLD.id
      AND estado = 'disponible';

    -- Release credits that were consumed by this payment (saldo-positivo usage)
    UPDATE patient_credits
    SET estado = 'disponible',
        usado_en_pago_id = NULL,
        actualizado_en = NOW()
    WHERE usado_en_pago_id = OLD.id
      AND estado = 'usado';

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_handle_payment_delete_credit ON payments;
CREATE TRIGGER trigger_handle_payment_delete_credit
    BEFORE DELETE ON payments
    FOR EACH ROW
    EXECUTE FUNCTION handle_payment_delete_credit();

-- Also: the overpayment calculator must only count CASH against the treatment
-- total. A saldo-positivo (credit application) must never generate a credit of
-- its own, otherwise inserting a saldo payment could inflate the paid amount.
CREATE OR REPLACE FUNCTION handle_overpayment_credit()
RETURNS TRIGGER AS $$
DECLARE
    v_total_final DECIMAL(10,2);
    v_total_paid DECIMAL(10,2);
    v_overpayment DECIMAL(10,2);
    v_paciente_id UUID;
    v_moneda VARCHAR(3);
BEGIN
    -- Get treatment info
    SELECT tc.total_final, tc.paciente_id, tc.moneda
    INTO v_total_final, v_paciente_id, v_moneda
    FROM tratamientos_completados tc
    WHERE tc.id = NEW.tratamiento_completado_id;

    IF v_total_final IS NULL THEN
        RETURN NEW;
    END IF;

    -- Calculate total paid including this new payment, excluding credit
    -- applications (metodo_pago = 'saldo_positivo').
    SELECT COALESCE(SUM(
        CASE
            WHEN monto_convertido IS NOT NULL THEN monto_convertido
            ELSE monto_pago
        END
    ), 0)
    INTO v_total_paid
    FROM payments
    WHERE tratamiento_completado_id = NEW.tratamiento_completado_id
      AND COALESCE(LOWER(metodo_pago), '') <> 'saldo_positivo';

    -- If overpaid, create credit for the difference
    v_overpayment := v_total_paid - v_total_final;
    IF v_overpayment > 0 THEN
        INSERT INTO patient_credits (paciente_id, monto, moneda, origen_pago_id, tratamiento_completado_id, estado, notas)
        VALUES (
            v_paciente_id,
            v_overpayment,
            v_moneda,
            NEW.id,
            NEW.tratamiento_completado_id,
            'disponible',
            'Saldo positivo generado por sobre-pago'
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;